# Workflow 이름 설정
name: Github Actions 실행시켜보기

# main이라는 브랜치에 push 될 때 아리 workflow 실행
on:
  push:
    branches:
      - main

# 하나의 workflow는 1개 이상의 job으로 구성됨
# 여러 job은 기본적으로 병렬적으로 수행됨
jobs:
  # job을 식별하기 위한 id
  My-Deploy-Job:
    # ubuntu 환경 가장 최신버전
    runs-on: ubuntu-latest

    # setp : 특정 작업을 수행하는 가장 작은 단위
    # job은 여러 step들로 구성되어 있음
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문작 작성하기
        run: |
          echo "Good"
          echo "Morning"